#This is a sample build configuration for Python.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

version: 2
jobs:
  build:
    docker:
       - image: python:3.7-slim
    steps:
       - checkout
       - run: pip install -r requirements.txt
