# Generated by Django 2.1.7 on 2019-08-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('engine', 'Engine System'), ('suspension', 'Suspension System'), ('transmission', 'Transmission System'), ('steering', 'Steering System'), ('electric', 'Electric System'), ('breaks', 'Brakes system'), ('body', 'Car Body')], default=None, help_text="Service's category'", max_length=128, verbose_name='name'),
        ),
    ]
