# Generated by Django 2.1.7 on 2019-08-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('engine', 'Engine System'), ('suspension', 'Suspension System'), ('transmission', 'Transmission System'), ('steering', 'Steering System'), ('electric', 'Electric System'), ('breaks', 'Brakes system'), ('body', 'Car Body')], default=None, help_text="Service's category", max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text="Service's name", max_length=128, verbose_name='name'),
        ),
    ]
