# Generated by Django 2.1.7 on 2019-06-03 22:20

import accounts.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fraud', models.BooleanField(db_index=True, default=False, verbose_name='Is fraud')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=accounts.models.get_username, unique_with=('company__name',))),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
