# Generated by Django 2.1.7 on 2019-08-22 05:23

import accounts.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_company',
        ),
        migrations.AddField(
            model_name='account',
            name='is_owner',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks if the user is owner is a service provider.', verbose_name='Is owner'),
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=['datetime', 'timezone'], editable=False, populate_from=accounts.models.get_username, unique_with=('company__name',)),
            preserve_default=False,
        ),
    ]
