# Generated by Django 2.1.7 on 2019-08-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190822_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(default=None, help_text='Companies related to this account', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='companies.Company'),
        ),
    ]
