# Generated by Django 2.1.7 on 2019-06-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190603_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
    ]
