# Generated by Django 2.1.7 on 2019-06-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('accounts', '0002_auto_20190613_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vehicles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle'),
        ),
    ]
