django:
  debug: true
  allowed_hosts: '[*]'
  ratelimit: false

databases:
  default:
    ENGINE: 'django.db.backends.postgresql'
    NAME: 'mydb_cars'
    USER: 'mydbusercars'
    PASSWORD: 'mydbpass'
    HOST: 'localhost'
    PORT: '5432'

celery:
  synchronous: true

secrets:
  secret_key: '*/super-mega-test-key*/'

conekta:
  private_key: 'key_PAAHsbnJ1hnhqmXGYFr5Bw'
  version: '2.0.0'

slack_notifications:
  public_channel: false
  private_channel: false

sentry:
  dsn: 'https://e523ba47d936485ca2570e5741d1f7ad@sentry.io/1366213'
