# Generated by Django 2.1.7 on 2019-06-13 05:16

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('admins', models.ManyToManyField(default=None, related_name='companies', to='accounts.Account')),
            ],
            options={
                'verbose_name': ('company',),
                'verbose_name_plural': 'companies',
            },
        ),
    ]
