# Generated by Django 2.1.7 on 2019-06-18 05:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('name', models.CharField(help_text="Compani's name", max_length=128, verbose_name='name')),
                ('address', models.CharField(default=None, help_text='physical address', max_length=128, verbose_name='address')),
                ('state', models.CharField(default=None, help_text='State', max_length=128, null=True, verbose_name='state')),
                ('country', models.CharField(default='mx', help_text='country', max_length=12, null=True, verbose_name='country')),
                ('phone', models.CharField(max_length=128, verbose_name='phone')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('admin', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='accounts.Account')),
            ],
            options={
                'verbose_name': ('company',),
                'verbose_name_plural': 'companies',
            },
        ),
    ]
