# Generated by Django 2.1.7 on 2019-06-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': ('company',), 'verbose_name_plural': 'companies'},
        ),
    ]
