# Generated by Django 2.1.7 on 2019-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='companies', to='accounts.Account'),
        ),
    ]
