# Generated by Django 2.1.7 on 2019-08-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company name', max_length=128, verbose_name='name'),
        ),
    ]
