# Generated by Django 2.1.7 on 2019-06-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190613_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='default addres', max_length=128, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=3345434645, max_length=128, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
