# Generated by Django 2.1.7 on 2019-06-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190618_0553'),
        ('companies', '0002_auto_20190618_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admin',
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.ManyToManyField(default=None, related_name='admins', to='accounts.Account'),
        ),
    ]
