# Generated by Django 2.1.7 on 2019-06-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190604_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admins',
        ),
    ]
