# Generated by Django 2.1.7 on 2019-06-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20190618_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='admin',
            new_name='admins',
        ),
    ]
