# Generated by Django 2.1.7 on 2019-06-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_company'),
        ('companies', '0003_remove_company_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='companies', to='accounts.Account'),
        ),
    ]
