# Generated by Django 2.1.7 on 2019-06-18 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190618_0553'),
        ('companies', '0004_auto_20190618_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admins',
        ),
        migrations.AddField(
            model_name='company',
            name='admins',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='accounts.Account'),
        ),
    ]
