# Generated by Django 2.1.7 on 2019-06-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('plates', models.CharField(max_length=32, verbose_name='plates')),
                ('brand', models.CharField(max_length=32, verbose_name='brand')),
                ('type', models.CharField(max_length=32, verbose_name='type')),
                ('model', models.CharField(max_length=32, verbose_name='model')),
            ],
            options={
                'verbose_name': ('vehicle',),
                'verbose_name_plural': 'vehicles',
            },
        ),
    ]
