# Generated by Django 2.1.7 on 2019-06-28 06:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('plates', models.CharField(max_length=32, verbose_name='plates')),
                ('brand', models.CharField(choices=[('honda', 'Honda'), ('bmw', 'BMW'), ('kia', 'kia'), ('mazda', 'Mazda'), ('vw', 'Volkswagen'), ('tesla', 'Tesla'), ('nissan', 'Nissan')], default='vw', max_length=12, verbose_name='brand')),
                ('type', models.CharField(max_length=32, verbose_name='type')),
                ('model', models.PositiveIntegerField(default=2019, help_text='Model year format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)], verbose_name='model')),
                ('account', models.ForeignKey(default=None, help_text='Where this vehicle belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'verbose_name': ('vehicle',),
                'verbose_name_plural': 'vehicles',
            },
        ),
    ]
