# Generated by Django 2.1.7 on 2019-08-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190822_0554'),
        ('vehicles', '0002_auto_20190822_0532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('plates', 'account')},
        ),
    ]
